language: java
sudo: false # faster builds

jdk:
  - openjdk8 

script:
  - mvn clean package
  - mvn test

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - mvn clean test jacoco:report coveralls:report
  - mvn clean test saga:coverage coveralls:report
  - mvn clean test saga:coverage cobertura:cobertura coveralls:report